version: '3.7'

volumes:
    logs:
        driver: local

services:
    slim:
        build:
            context: .
            dockerfile: Dockerfile
        image: phpds:local
        environment:
            APP_ENV: production
            PORT: 8080
            docker: "true"
        ports:
            - "8080:8080"
        volumes:
            - logs:/var/www/logs
